# This is a basic workflow to help you get started with Actions

name: Extractor

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    
  # This workflow contains a single job called "build"
  build:
    if: contains(github.event.issue.labels.*.name, 'new project')
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 2.7


    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build 

    - name: Build with Gradle
      run: ./gradlew jar

    - name: Build with Gradle
      run: ./gradlew fatJar
    
    - name: ls
      run: ls -R
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: jar
        # A file, directory or wildcard pattern that describes what to upload
        path: ./build/libs/jasome.jar


    - name: Grant execute permission for jasome
      run: chmod +x ./jasome


    - name: Checkout tools repo
      continue-on-error: true
      uses: actions/checkout@v2
      with:
        repository: ${{github.event.issue.title}}
        path: ./my-tools
        fetch-depth: 0
    
    - name: fetch  
      continue-on-error: true
      run: git fetch
      working-directory: ./my-tools

    - name: Checkout tools repo
      run: python -c "import sys,os;os.system('git checkout ' + sys.argv[1].strip())" ${{github.event.issue.body}}
      working-directory: ./my-tools

    - name: execute
      run: java -Xmx6g -Xss8096k -cp build/libs/jasome_runner.jar org.jasome.executive.CommandLineExecutive -xt my-tools -o output.xml
    
    - name: Upload a jasome_runner Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: jasome_runner.jar
        # A file, directory or wildcard pattern that describes what to upload
        path: build/libs/jasome_runner.jar

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: ${{github.event.issue.number}}.xml
        # A file, directory or wildcard pattern that describes what to upload
        path: output.xml

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: output.xml
        asset_name: ${{github.event.issue.number}}.xml
        tag: ${{github.event.issue.number}}

    - name: Add closed issue comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: The extracted data can be found at https://github.com/amir9979/jasome_runner/releases by number  ${{github.event.issue.number}}.


    - name: Close Issue
      continue-on-error: true
      uses: peter-evans/close-issue@v1
      with:
        comment: |
          The issue you have reported seems to be resolved now.
          The extracted data can be found at https://github.com/amir9979/jasome_runner/releases by number  ${{github.event.issue.number}}.

