name: Data Extractor 

on:
  issues:
    types: [opened]

jobs:
   
  build:

    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'new project')
    steps:
    - name: log
    - run: echo working on repo ${{github.event.issue.title}} at tag ${{github.event.issue.body}}
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build 

    - name: Build with Gradle
      run: ./gradlew fatJar
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: jar
        # A file, directory or wildcard pattern that describes what to upload
        path: ./build/libs/jasome.jar
    
    - name: Grant execute permission for jasome
      run: chmod +x ./jasome


    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: ${{github.event.issue.title}}
        path: ./my-tools
        fetch-depth: 0
        ref: fop-2_1
        
    - name: Checkout tools repo
      run: git checkout ${{github.event.issue.body}}
      working-directory: ./my-tools

    - name: execute
      run: ./jasome ./my-tools/ -o output.xml
    

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: ${{github.event.issue.title}}_${{github.event.issue.body}}.xml
        # A file, directory or wildcard pattern that describes what to upload
        path: output.xml

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: output.xml
        asset_name: ${{github.event.issue.title}}_${{github.event.issue.body}}.xml
        tag: ${{ github.ref }}
        overwrite: true
    
    - name: Close Issue
      uses: peter-evans/close-issue@v1
      with:
        comment: |
          The issue you have reported seems to be resolved now.
          The new projects data can be found at releases
